<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Bạn chắc chắn muốn import thiết bị không?' => '',
    'Bạn có muốn tạm dừng đại lý này không?' => '',
    'Bạn có muốn xóa không?' => '',
    'Bạn xóa thiết bị này không?' => '',
    'Chuyển đại lý' => '',
    'Create' => '',
    'Create Subscriber Activity' => '',
    'Create Subscriber Device Asm' => '',
    'Cập nhật' => '',
    'Danh sách thiết bị' => '',
    'Delete' => '',
    'Email' => '',
    'Họ và tên' => '',
    'ID' => '',
    'Import thiết bị' => '',
    'Mã đại lý' => '',
    'Mô tả' => '',
    'Mật khẩu' => '',
    'Người quản lý' => '',
    'Reset' => '',
    'Search' => '',
    'Site' => '',
    'Sort' => '',
    'Subscriber Activities' => '',
    'Subscriber Device Asms' => '',
    'Số điện thoại' => '',
    'Sửa thông tin {modelClass}: ' => '',
    'Trạng thái' => '',
    'Tên tài khoản' => '',
    'Tên đại lý' => '',
    'Tạm dừng' => '',
    'Tạo thiết bị' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Xác nhận mật khẩu' => '',
    'Xóa' => '',
    'Xóa người dùng này?' => '',
    'Địa chỉ' => '',
];
